### PR TITLE
[Consider] adding `-page` suffix to front end apps

### PR DESCRIPTION
**Pull request by matthew-andrews**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
e.g next-front-page, next-article-page, etc

**Comment by commuterjoy** [comment]
Doesn't work in all cases - Eg. beacon-dashboard-page (is actually a series of pages)

I wonder if there's a distinction between a user-facing page sat behind the router and a self-contained app?

- next-beacon-dashboard-app
- next-article-page

**Comment by tom-parker** [comment]
This also leads us down the route of only every having single purpose user-facing apps. Is that something we definitely want? I'm happy to go with that but it does restrict us slightly.

**Comment by matthew-andrews** [comment]
Yeah you're right…  Happy to make this `-page` suffix for all customer facing apps.  Non-customer facing apps (since there are so few) can continue have no convention for now……  Not a fan of ‘app’ because almost everything is an app.

**Comment by matthew-andrews** [comment]
Is that ok? @tom-parker / @commuterjoy

**Comment by tom-parker** [comment]
@matthew-andrews yeah I'm happy to go with that. Although this does mean we're essentially stating the convention is for one customer facing app to serve one customer facing page?

**Comment by matthew-andrews** [comment]
One type of page?  Kind of how we have now…… front-page, article-page, stream-page, my-page, opt-in-page…………


Hmm…… it doesn't make sense for `next-assets` though :disappointed: or search suggestions API……

Although perhaps those two shouldn't be behind the router :smile:

**Comment by commuterjoy** [comment]
yup, i think -page is for stuff behind the router.

**Comment by matthew-andrews** [comment]
think `next-assets` is basically not used behind the router anymore and search suggestions shouldn't be either.

**Pull request merged**
