### PR TITLE
Add basic new starter process

### PR DESCRIPTION
**Pull request by matthew-andrews**
// @commuterjoy 

@ironsidevsquincy could you flesh this out as / when you find things you need?

### CODE REVIEW

**Comment by keirog** [comment]
Maybe add something about using Slack?

**Comment by matthew-andrews** [comment]
@keirog yes!

**Comment by captain-sysadmin** [comment]
* sharing the google drive folder with the sexy diagrams
* http://financial-times.github.io/next/docs/developer-guide
* sign up to github, slack, heroku, et al (and make sure that they've been joined into the right group)
* SSH keys?

**Comment by matthew-andrews** [comment]
- yes
- hmm, i think if they found this doc they'd have found that
- done
- ssh keys?

**Comment by captain-sysadmin** [comment]
(should have used an ordered list...)
I only found the dev guide by accident, hence my enthusiasm.

**Comment by matthew-andrews** [comment]
that's a happy accident @captain-sysadmin  :smile:

**Pull request merged**
